version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "Europe/Vienna"

    open-pull-requests-limit: 5

    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"

    groups:
      nextjs:
        patterns:
          - "next"
      react:
        patterns:
          - "react"
          - "react-dom"
      styling:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "postcss"
      general:
        patterns:
          - "*"
